// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Antenatalinformation is the predicate function for antenatalinformation builders.
type Antenatalinformation func(*sql.Selector)

// Bonedisease is the predicate function for bonedisease builders.
type Bonedisease func(*sql.Selector)

// Checksymptoms is the predicate function for checksymptoms builders.
type Checksymptoms func(*sql.Selector)

// Dentalappointment is the predicate function for dentalappointment builders.
type Dentalappointment func(*sql.Selector)

// Dentalkind is the predicate function for dentalkind builders.
type Dentalkind func(*sql.Selector)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// DoctorOrderSheet is the predicate function for doctorordersheet builders.
type DoctorOrderSheet func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Personnel is the predicate function for personnel builders.
type Personnel func(*sql.Selector)

// Physicaltherapyrecord is the predicate function for physicaltherapyrecord builders.
type Physicaltherapyrecord func(*sql.Selector)

// Physicaltherapyroom is the predicate function for physicaltherapyroom builders.
type Physicaltherapyroom func(*sql.Selector)

// Pregnancystatus is the predicate function for pregnancystatus builders.
type Pregnancystatus func(*sql.Selector)

// Remedy is the predicate function for remedy builders.
type Remedy func(*sql.Selector)

// Risks is the predicate function for risks builders.
type Risks func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)

// Surgeryappointment is the predicate function for surgeryappointment builders.
type Surgeryappointment func(*sql.Selector)

// Surgerytype is the predicate function for surgerytype builders.
type Surgerytype func(*sql.Selector)
