// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/to63/app/ent/checksymptom"
	"github.com/to63/app/ent/disease"
	"github.com/to63/app/ent/doctorordersheet"
	"github.com/to63/app/ent/patient"
	"github.com/to63/app/ent/personnel"
)

// ChecksymptomCreate is the builder for creating a Checksymptom entity.
type ChecksymptomCreate struct {
	config
	mutation *ChecksymptomMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (cc *ChecksymptomCreate) SetDate(t time.Time) *ChecksymptomCreate {
	cc.mutation.SetDate(t)
	return cc
}

// SetTimes sets the "times" field.
func (cc *ChecksymptomCreate) SetTimes(s string) *ChecksymptomCreate {
	cc.mutation.SetTimes(s)
	return cc
}

// SetNote sets the "note" field.
func (cc *ChecksymptomCreate) SetNote(s string) *ChecksymptomCreate {
	cc.mutation.SetNote(s)
	return cc
}

// SetPatientID sets the "patient" edge to the Patient entity by ID.
func (cc *ChecksymptomCreate) SetPatientID(id int) *ChecksymptomCreate {
	cc.mutation.SetPatientID(id)
	return cc
}

// SetNillablePatientID sets the "patient" edge to the Patient entity by ID if the given value is not nil.
func (cc *ChecksymptomCreate) SetNillablePatientID(id *int) *ChecksymptomCreate {
	if id != nil {
		cc = cc.SetPatientID(*id)
	}
	return cc
}

// SetPatient sets the "patient" edge to the Patient entity.
func (cc *ChecksymptomCreate) SetPatient(p *Patient) *ChecksymptomCreate {
	return cc.SetPatientID(p.ID)
}

// SetPersonnelID sets the "personnel" edge to the Personnel entity by ID.
func (cc *ChecksymptomCreate) SetPersonnelID(id int) *ChecksymptomCreate {
	cc.mutation.SetPersonnelID(id)
	return cc
}

// SetNillablePersonnelID sets the "personnel" edge to the Personnel entity by ID if the given value is not nil.
func (cc *ChecksymptomCreate) SetNillablePersonnelID(id *int) *ChecksymptomCreate {
	if id != nil {
		cc = cc.SetPersonnelID(*id)
	}
	return cc
}

// SetPersonnel sets the "personnel" edge to the Personnel entity.
func (cc *ChecksymptomCreate) SetPersonnel(p *Personnel) *ChecksymptomCreate {
	return cc.SetPersonnelID(p.ID)
}

// SetDoctorordersheetID sets the "doctorordersheet" edge to the Doctorordersheet entity by ID.
func (cc *ChecksymptomCreate) SetDoctorordersheetID(id int) *ChecksymptomCreate {
	cc.mutation.SetDoctorordersheetID(id)
	return cc
}

// SetNillableDoctorordersheetID sets the "doctorordersheet" edge to the Doctorordersheet entity by ID if the given value is not nil.
func (cc *ChecksymptomCreate) SetNillableDoctorordersheetID(id *int) *ChecksymptomCreate {
	if id != nil {
		cc = cc.SetDoctorordersheetID(*id)
	}
	return cc
}

// SetDoctorordersheet sets the "doctorordersheet" edge to the Doctorordersheet entity.
func (cc *ChecksymptomCreate) SetDoctorordersheet(d *Doctorordersheet) *ChecksymptomCreate {
	return cc.SetDoctorordersheetID(d.ID)
}

// SetDiseaseID sets the "disease" edge to the Disease entity by ID.
func (cc *ChecksymptomCreate) SetDiseaseID(id int) *ChecksymptomCreate {
	cc.mutation.SetDiseaseID(id)
	return cc
}

// SetNillableDiseaseID sets the "disease" edge to the Disease entity by ID if the given value is not nil.
func (cc *ChecksymptomCreate) SetNillableDiseaseID(id *int) *ChecksymptomCreate {
	if id != nil {
		cc = cc.SetDiseaseID(*id)
	}
	return cc
}

// SetDisease sets the "disease" edge to the Disease entity.
func (cc *ChecksymptomCreate) SetDisease(d *Disease) *ChecksymptomCreate {
	return cc.SetDiseaseID(d.ID)
}

// Mutation returns the ChecksymptomMutation object of the builder.
func (cc *ChecksymptomCreate) Mutation() *ChecksymptomMutation {
	return cc.mutation
}

// Save creates the Checksymptom in the database.
func (cc *ChecksymptomCreate) Save(ctx context.Context) (*Checksymptom, error) {
	var (
		err  error
		node *Checksymptom
	)
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChecksymptomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChecksymptomCreate) SaveX(ctx context.Context) *Checksymptom {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChecksymptomCreate) check() error {
	if _, ok := cc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New("ent: missing required field \"date\"")}
	}
	if _, ok := cc.mutation.Times(); !ok {
		return &ValidationError{Name: "times", err: errors.New("ent: missing required field \"times\"")}
	}
	if v, ok := cc.mutation.Times(); ok {
		if err := checksymptom.TimesValidator(v); err != nil {
			return &ValidationError{Name: "times", err: fmt.Errorf("ent: validator failed for field \"times\": %w", err)}
		}
	}
	if _, ok := cc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New("ent: missing required field \"note\"")}
	}
	if v, ok := cc.mutation.Note(); ok {
		if err := checksymptom.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf("ent: validator failed for field \"note\": %w", err)}
		}
	}
	return nil
}

func (cc *ChecksymptomCreate) sqlSave(ctx context.Context) (*Checksymptom, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cc *ChecksymptomCreate) createSpec() (*Checksymptom, *sqlgraph.CreateSpec) {
	var (
		_node = &Checksymptom{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: checksymptom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: checksymptom.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.Date(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: checksymptom.FieldDate,
		})
		_node.Date = value
	}
	if value, ok := cc.mutation.Times(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: checksymptom.FieldTimes,
		})
		_node.Times = value
	}
	if value, ok := cc.mutation.Note(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: checksymptom.FieldNote,
		})
		_node.Note = value
	}
	if nodes := cc.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checksymptom.PatientTable,
			Columns: []string{checksymptom.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.PersonnelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checksymptom.PersonnelTable,
			Columns: []string{checksymptom.PersonnelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personnel.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.DoctorordersheetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checksymptom.DoctorordersheetTable,
			Columns: []string{checksymptom.DoctorordersheetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctorordersheet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.DiseaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checksymptom.DiseaseTable,
			Columns: []string{checksymptom.DiseaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: disease.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChecksymptomCreateBulk is the builder for creating many Checksymptom entities in bulk.
type ChecksymptomCreateBulk struct {
	config
	builders []*ChecksymptomCreate
}

// Save creates the Checksymptom entities in the database.
func (ccb *ChecksymptomCreateBulk) Save(ctx context.Context) ([]*Checksymptom, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Checksymptom, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChecksymptomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChecksymptomCreateBulk) SaveX(ctx context.Context) []*Checksymptom {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
