// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/to63/app/ent/surgeryappointment"
	"github.com/to63/app/ent/surgerytype"
)

// SurgerytypeCreate is the builder for creating a Surgerytype entity.
type SurgerytypeCreate struct {
	config
	mutation *SurgerytypeMutation
	hooks    []Hook
}

// SetTypename sets the "typename" field.
func (sc *SurgerytypeCreate) SetTypename(s string) *SurgerytypeCreate {
	sc.mutation.SetTypename(s)
	return sc
}

// SetSurgeryappointmentID sets the "Surgeryappointment" edge to the Surgeryappointment entity by ID.
func (sc *SurgerytypeCreate) SetSurgeryappointmentID(id int) *SurgerytypeCreate {
	sc.mutation.SetSurgeryappointmentID(id)
	return sc
}

// SetNillableSurgeryappointmentID sets the "Surgeryappointment" edge to the Surgeryappointment entity by ID if the given value is not nil.
func (sc *SurgerytypeCreate) SetNillableSurgeryappointmentID(id *int) *SurgerytypeCreate {
	if id != nil {
		sc = sc.SetSurgeryappointmentID(*id)
	}
	return sc
}

// SetSurgeryappointment sets the "Surgeryappointment" edge to the Surgeryappointment entity.
func (sc *SurgerytypeCreate) SetSurgeryappointment(s *Surgeryappointment) *SurgerytypeCreate {
	return sc.SetSurgeryappointmentID(s.ID)
}

// Mutation returns the SurgerytypeMutation object of the builder.
func (sc *SurgerytypeCreate) Mutation() *SurgerytypeMutation {
	return sc.mutation
}

// Save creates the Surgerytype in the database.
func (sc *SurgerytypeCreate) Save(ctx context.Context) (*Surgerytype, error) {
	var (
		err  error
		node *Surgerytype
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SurgerytypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SurgerytypeCreate) SaveX(ctx context.Context) *Surgerytype {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (sc *SurgerytypeCreate) check() error {
	if _, ok := sc.mutation.Typename(); !ok {
		return &ValidationError{Name: "typename", err: errors.New("ent: missing required field \"typename\"")}
	}
	if v, ok := sc.mutation.Typename(); ok {
		if err := surgerytype.TypenameValidator(v); err != nil {
			return &ValidationError{Name: "typename", err: fmt.Errorf("ent: validator failed for field \"typename\": %w", err)}
		}
	}
	return nil
}

func (sc *SurgerytypeCreate) sqlSave(ctx context.Context) (*Surgerytype, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *SurgerytypeCreate) createSpec() (*Surgerytype, *sqlgraph.CreateSpec) {
	var (
		_node = &Surgerytype{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: surgerytype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: surgerytype.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Typename(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: surgerytype.FieldTypename,
		})
		_node.Typename = value
	}
	if nodes := sc.mutation.SurgeryappointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   surgerytype.SurgeryappointmentTable,
			Columns: []string{surgerytype.SurgeryappointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: surgeryappointment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SurgerytypeCreateBulk is the builder for creating many Surgerytype entities in bulk.
type SurgerytypeCreateBulk struct {
	config
	builders []*SurgerytypeCreate
}

// Save creates the Surgerytype entities in the database.
func (scb *SurgerytypeCreateBulk) Save(ctx context.Context) ([]*Surgerytype, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Surgerytype, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SurgerytypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SurgerytypeCreateBulk) SaveX(ctx context.Context) []*Surgerytype {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
