// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/to63/app/ent/surgeryappointment"
	"github.com/to63/app/ent/surgerytype"
)

// Surgerytype is the model entity for the Surgerytype schema.
type Surgerytype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Typename holds the value of the "typename" field.
	Typename string `json:"typename,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SurgerytypeQuery when eager-loading is set.
	Edges SurgerytypeEdges `json:"edges"`
}

// SurgerytypeEdges holds the relations/edges for other nodes in the graph.
type SurgerytypeEdges struct {
	// Surgeryappointment holds the value of the Surgeryappointment edge.
	Surgeryappointment *Surgeryappointment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SurgeryappointmentOrErr returns the Surgeryappointment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SurgerytypeEdges) SurgeryappointmentOrErr() (*Surgeryappointment, error) {
	if e.loadedTypes[0] {
		if e.Surgeryappointment == nil {
			// The edge Surgeryappointment was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: surgeryappointment.Label}
		}
		return e.Surgeryappointment, nil
	}
	return nil, &NotLoadedError{edge: "Surgeryappointment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Surgerytype) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case surgerytype.FieldID:
			values[i] = &sql.NullInt64{}
		case surgerytype.FieldTypename:
			values[i] = &sql.NullString{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Surgerytype", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Surgerytype fields.
func (s *Surgerytype) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case surgerytype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case surgerytype.FieldTypename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field typename", values[i])
			} else if value.Valid {
				s.Typename = value.String
			}
		}
	}
	return nil
}

// QuerySurgeryappointment queries the "Surgeryappointment" edge of the Surgerytype entity.
func (s *Surgerytype) QuerySurgeryappointment() *SurgeryappointmentQuery {
	return (&SurgerytypeClient{config: s.config}).QuerySurgeryappointment(s)
}

// Update returns a builder for updating this Surgerytype.
// Note that you need to call Surgerytype.Unwrap() before calling this method if this Surgerytype
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Surgerytype) Update() *SurgerytypeUpdateOne {
	return (&SurgerytypeClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Surgerytype entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Surgerytype) Unwrap() *Surgerytype {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Surgerytype is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Surgerytype) String() string {
	var builder strings.Builder
	builder.WriteString("Surgerytype(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", typename=")
	builder.WriteString(s.Typename)
	builder.WriteByte(')')
	return builder.String()
}

// Surgerytypes is a parsable slice of Surgerytype.
type Surgerytypes []*Surgerytype

func (s Surgerytypes) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
