// Code generated by entc, DO NOT EDIT.

package antenatalinformation

const (
	// Label holds the string label denoting the antenatalinformation type in the database.
	Label = "antenatalinformation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGestationalage holds the string denoting the gestationalage field in the database.
	FieldGestationalage = "gestationalage"
	// FieldExaminationresult holds the string denoting the examinationresult field in the database.
	FieldExaminationresult = "examinationresult"
	// FieldAdvice holds the string denoting the advice field in the database.
	FieldAdvice = "advice"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"

	// EdgePersonnel holds the string denoting the personnel edge name in mutations.
	EdgePersonnel = "Personnel"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "Patient"
	// EdgePregnancystatus holds the string denoting the pregnancystatus edge name in mutations.
	EdgePregnancystatus = "Pregnancystatus"
	// EdgeRisks holds the string denoting the risks edge name in mutations.
	EdgeRisks = "Risks"

	// Table holds the table name of the antenatalinformation in the database.
	Table = "antenatalinformations"
	// PersonnelTable is the table the holds the Personnel relation/edge.
	PersonnelTable = "antenatalinformations"
	// PersonnelInverseTable is the table name for the Personnel entity.
	// It exists in this package in order to avoid circular dependency with the "personnel" package.
	PersonnelInverseTable = "personnels"
	// PersonnelColumn is the table column denoting the Personnel relation/edge.
	PersonnelColumn = "Personnel_id"
	// PatientTable is the table the holds the Patient relation/edge.
	PatientTable = "antenatalinformations"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the Patient relation/edge.
	PatientColumn = "Patient_id"
	// PregnancystatusTable is the table the holds the Pregnancystatus relation/edge.
	PregnancystatusTable = "antenatalinformations"
	// PregnancystatusInverseTable is the table name for the Pregnancystatus entity.
	// It exists in this package in order to avoid circular dependency with the "pregnancystatus" package.
	PregnancystatusInverseTable = "pregnancystatuses"
	// PregnancystatusColumn is the table column denoting the Pregnancystatus relation/edge.
	PregnancystatusColumn = "pregnancystatus_antenatalinformation"
	// RisksTable is the table the holds the Risks relation/edge.
	RisksTable = "antenatalinformations"
	// RisksInverseTable is the table name for the Risks entity.
	// It exists in this package in order to avoid circular dependency with the "risks" package.
	RisksInverseTable = "risks"
	// RisksColumn is the table column denoting the Risks relation/edge.
	RisksColumn = "risks_antenatalinformation"
)

// Columns holds all SQL columns for antenatalinformation fields.
var Columns = []string{
	FieldID,
	FieldGestationalage,
	FieldExaminationresult,
	FieldAdvice,
	FieldTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Antenatalinformation type.
var ForeignKeys = []string{
	"Patient_id",
	"Personnel_id",
	"pregnancystatus_antenatalinformation",
	"risks_antenatalinformation",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// GestationalageValidator is a validator for the "gestationalage" field. It is called by the builders before save.
	GestationalageValidator func(int) error
	// ExaminationresultValidator is a validator for the "examinationresult" field. It is called by the builders before save.
	ExaminationresultValidator func(string) error
	// AdviceValidator is a validator for the "advice" field. It is called by the builders before save.
	AdviceValidator func(string) error
)
