/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBonedisease
 */
export interface ControllersBonedisease {
    /**
     * 
     * @type {string}
     * @memberof ControllersBonedisease
     */
    addedTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersBonedisease
     */
    advice?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersBonedisease
     */
    identificationCard?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBonedisease
     */
    patientID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBonedisease
     */
    personnelID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBonedisease
     */
    remedyID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBonedisease
     */
    tel?: string;
}

export function ControllersBonediseaseFromJSON(json: any): ControllersBonedisease {
    return ControllersBonediseaseFromJSONTyped(json, false);
}

export function ControllersBonediseaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBonedisease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'addedTime') ? undefined : json['addedTime'],
        'advice': !exists(json, 'advice') ? undefined : json['advice'],
        'identificationCard': !exists(json, 'identificationCard') ? undefined : json['identificationCard'],
        'patientID': !exists(json, 'patientID') ? undefined : json['patientID'],
        'personnelID': !exists(json, 'personnelID') ? undefined : json['personnelID'],
        'remedyID': !exists(json, 'remedyID') ? undefined : json['remedyID'],
        'tel': !exists(json, 'tel') ? undefined : json['tel'],
    };
}

export function ControllersBonediseaseToJSON(value?: ControllersBonedisease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedTime': value.addedTime,
        'advice': value.advice,
        'identificationCard': value.identificationCard,
        'patientID': value.patientID,
        'personnelID': value.personnelID,
        'remedyID': value.remedyID,
        'tel': value.tel,
    };
}


