/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersChecksymptom
 */
export interface ControllersChecksymptom {
    /**
     * 
     * @type {string}
     * @memberof ControllersChecksymptom
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersChecksymptom
     */
    diseaseID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersChecksymptom
     */
    doctorordersheetID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersChecksymptom
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersChecksymptom
     */
    patientID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersChecksymptom
     */
    personnelID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersChecksymptom
     */
    times?: string;
}

export function ControllersChecksymptomFromJSON(json: any): ControllersChecksymptom {
    return ControllersChecksymptomFromJSONTyped(json, false);
}

export function ControllersChecksymptomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersChecksymptom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'diseaseID': !exists(json, 'diseaseID') ? undefined : json['diseaseID'],
        'doctorordersheetID': !exists(json, 'doctorordersheetID') ? undefined : json['doctorordersheetID'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'patientID': !exists(json, 'patientID') ? undefined : json['patientID'],
        'personnelID': !exists(json, 'personnelID') ? undefined : json['personnelID'],
        'times': !exists(json, 'times') ? undefined : json['times'],
    };
}

export function ControllersChecksymptomToJSON(value?: ControllersChecksymptom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'diseaseID': value.diseaseID,
        'doctorordersheetID': value.doctorordersheetID,
        'note': value.note,
        'patientID': value.patientID,
        'personnelID': value.personnelID,
        'times': value.times,
    };
}


