/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersSurgeryappointment
 */
export interface ControllersSurgeryappointment {
    /**
     * 
     * @type {string}
     * @memberof ControllersSurgeryappointment
     */
    appointtime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersSurgeryappointment
     */
    cost?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersSurgeryappointment
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersSurgeryappointment
     */
    patientid?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersSurgeryappointment
     */
    personelid?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersSurgeryappointment
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersSurgeryappointment
     */
    surgerytypeid?: number;
}

export function ControllersSurgeryappointmentFromJSON(json: any): ControllersSurgeryappointment {
    return ControllersSurgeryappointmentFromJSONTyped(json, false);
}

export function ControllersSurgeryappointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersSurgeryappointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointtime': !exists(json, 'appointtime') ? undefined : json['appointtime'],
        'cost': !exists(json, 'cost') ? undefined : json['cost'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'patientid': !exists(json, 'patientid') ? undefined : json['patientid'],
        'personelid': !exists(json, 'personelid') ? undefined : json['personelid'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'surgerytypeid': !exists(json, 'surgerytypeid') ? undefined : json['surgerytypeid'],
    };
}

export function ControllersSurgeryappointmentToJSON(value?: ControllersSurgeryappointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointtime': value.appointtime,
        'cost': value.cost,
        'note': value.note,
        'patientid': value.patientid,
        'personelid': value.personelid,
        'phone': value.phone,
        'surgerytypeid': value.surgerytypeid,
    };
}


