/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDentalappointment
 */
export interface ControllersDentalappointment {
    /**
     * 
     * @type {string}
     * @memberof ControllersDentalappointment
     */
    appointTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDentalappointment
     */
    kindName?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDentalappointment
     */
    patientID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDentalappointment
     */
    personnelID?: number;
}

export function ControllersDentalappointmentFromJSON(json: any): ControllersDentalappointment {
    return ControllersDentalappointmentFromJSONTyped(json, false);
}

export function ControllersDentalappointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDentalappointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointTime': !exists(json, 'appointTime') ? undefined : json['appointTime'],
        'kindName': !exists(json, 'kindName') ? undefined : json['kindName'],
        'patientID': !exists(json, 'patientID') ? undefined : json['patientID'],
        'personnelID': !exists(json, 'personnelID') ? undefined : json['personnelID'],
    };
}

export function ControllersDentalappointmentToJSON(value?: ControllersDentalappointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointTime': value.appointTime,
        'kindName': value.kindName,
        'patientID': value.patientID,
        'personnelID': value.personnelID,
    };
}


