/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersAntenatalinformation
 */
export interface ControllersAntenatalinformation {
    /**
     * 
     * @type {number}
     * @memberof ControllersAntenatalinformation
     */
    gestationalage?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersAntenatalinformation
     */
    patient?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersAntenatalinformation
     */
    personnel?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersAntenatalinformation
     */
    pregnancystatus?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersAntenatalinformation
     */
    risks?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersAntenatalinformation
     */
    time?: string;
}

export function ControllersAntenatalinformationFromJSON(json: any): ControllersAntenatalinformation {
    return ControllersAntenatalinformationFromJSONTyped(json, false);
}

export function ControllersAntenatalinformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersAntenatalinformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gestationalage': !exists(json, 'gestationalage') ? undefined : json['gestationalage'],
        'patient': !exists(json, 'patient') ? undefined : json['patient'],
        'personnel': !exists(json, 'personnel') ? undefined : json['personnel'],
        'pregnancystatus': !exists(json, 'pregnancystatus') ? undefined : json['pregnancystatus'],
        'risks': !exists(json, 'risks') ? undefined : json['risks'],
        'time': !exists(json, 'time') ? undefined : json['time'],
    };
}

export function ControllersAntenatalinformationToJSON(value?: ControllersAntenatalinformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gestationalage': value.gestationalage,
        'patient': value.patient,
        'personnel': value.personnel,
        'pregnancystatus': value.pregnancystatus,
        'risks': value.risks,
        'time': value.time,
    };
}


