/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDisease,
    EntDiseaseFromJSON,
    EntDiseaseFromJSONTyped,
    EntDiseaseToJSON,
    EntDoctorordersheet,
    EntDoctorordersheetFromJSON,
    EntDoctorordersheetFromJSONTyped,
    EntDoctorordersheetToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntPersonnel,
    EntPersonnelFromJSON,
    EntPersonnelFromJSONTyped,
    EntPersonnelToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntChecksymptomEdges
 */
export interface EntChecksymptomEdges {
    /**
     * 
     * @type {EntDisease}
     * @memberof EntChecksymptomEdges
     */
    disease?: EntDisease;
    /**
     * 
     * @type {EntDoctorordersheet}
     * @memberof EntChecksymptomEdges
     */
    doctorordersheet?: EntDoctorordersheet;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntChecksymptomEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntPersonnel}
     * @memberof EntChecksymptomEdges
     */
    personnel?: EntPersonnel;
}

export function EntChecksymptomEdgesFromJSON(json: any): EntChecksymptomEdges {
    return EntChecksymptomEdgesFromJSONTyped(json, false);
}

export function EntChecksymptomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntChecksymptomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disease': !exists(json, 'Disease') ? undefined : EntDiseaseFromJSON(json['Disease']),
        'doctorordersheet': !exists(json, 'Doctorordersheet') ? undefined : EntDoctorordersheetFromJSON(json['Doctorordersheet']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'personnel': !exists(json, 'Personnel') ? undefined : EntPersonnelFromJSON(json['Personnel']),
    };
}

export function EntChecksymptomEdgesToJSON(value?: EntChecksymptomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disease': EntDiseaseToJSON(value.disease),
        'doctorordersheet': EntDoctorordersheetToJSON(value.doctorordersheet),
        'patient': EntPatientToJSON(value.patient),
        'personnel': EntPersonnelToJSON(value.personnel),
    };
}


