/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDentalappointmentEdges,
    EntDentalappointmentEdgesFromJSON,
    EntDentalappointmentEdgesFromJSONTyped,
    EntDentalappointmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDentalappointment
 */
export interface EntDentalappointment {
    /**
     * Amount holds the value of the "amount" field.
     * @type {number}
     * @memberof EntDentalappointment
     */
    amount?: number;
    /**
     * Appointtime holds the value of the "appointtime" field.
     * @type {string}
     * @memberof EntDentalappointment
     */
    appointtime?: string;
    /**
     * 
     * @type {EntDentalappointmentEdges}
     * @memberof EntDentalappointment
     */
    edges?: EntDentalappointmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDentalappointment
     */
    id?: number;
    /**
     * Note holds the value of the "note" field.
     * @type {string}
     * @memberof EntDentalappointment
     */
    note?: string;
    /**
     * Price holds the value of the "price" field.
     * @type {number}
     * @memberof EntDentalappointment
     */
    price?: number;
}

export function EntDentalappointmentFromJSON(json: any): EntDentalappointment {
    return EntDentalappointmentFromJSONTyped(json, false);
}

export function EntDentalappointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDentalappointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'appointtime': !exists(json, 'appointtime') ? undefined : json['appointtime'],
        'edges': !exists(json, 'edges') ? undefined : EntDentalappointmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'price': !exists(json, 'price') ? undefined : json['price'],
    };
}

export function EntDentalappointmentToJSON(value?: EntDentalappointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'appointtime': value.appointtime,
        'edges': EntDentalappointmentEdgesToJSON(value.edges),
        'id': value.id,
        'note': value.note,
        'price': value.price,
    };
}


