/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntChecksymptom,
    EntChecksymptomFromJSON,
    EntChecksymptomFromJSONTyped,
    EntChecksymptomToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDoctorordersheetEdges
 */
export interface EntDoctorordersheetEdges {
    /**
     * Checksymptom holds the value of the Checksymptom edge.
     * @type {Array<EntChecksymptom>}
     * @memberof EntDoctorordersheetEdges
     */
    checksymptom?: Array<EntChecksymptom>;
}

export function EntDoctorordersheetEdgesFromJSON(json: any): EntDoctorordersheetEdges {
    return EntDoctorordersheetEdgesFromJSONTyped(json, false);
}

export function EntDoctorordersheetEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDoctorordersheetEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checksymptom': !exists(json, 'checksymptom') ? undefined : ((json['checksymptom'] as Array<any>).map(EntChecksymptomFromJSON)),
    };
}

export function EntDoctorordersheetEdgesToJSON(value?: EntDoctorordersheetEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checksymptom': value.checksymptom === undefined ? undefined : ((value.checksymptom as Array<any>).map(EntChecksymptomToJSON)),
    };
}


