/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntPersonnel,
    EntPersonnelFromJSON,
    EntPersonnelFromJSONTyped,
    EntPersonnelToJSON,
    EntPhysicaltherapyroom,
    EntPhysicaltherapyroomFromJSON,
    EntPhysicaltherapyroomFromJSONTyped,
    EntPhysicaltherapyroomToJSON,
    EntStatus,
    EntStatusFromJSON,
    EntStatusFromJSONTyped,
    EntStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPhysicaltherapyrecordEdges
 */
export interface EntPhysicaltherapyrecordEdges {
    /**
     * 
     * @type {EntPatient}
     * @memberof EntPhysicaltherapyrecordEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntPersonnel}
     * @memberof EntPhysicaltherapyrecordEdges
     */
    personnel?: EntPersonnel;
    /**
     * 
     * @type {EntPhysicaltherapyroom}
     * @memberof EntPhysicaltherapyrecordEdges
     */
    physicaltherapyroom?: EntPhysicaltherapyroom;
    /**
     * 
     * @type {EntStatus}
     * @memberof EntPhysicaltherapyrecordEdges
     */
    status?: EntStatus;
}

export function EntPhysicaltherapyrecordEdgesFromJSON(json: any): EntPhysicaltherapyrecordEdges {
    return EntPhysicaltherapyrecordEdgesFromJSONTyped(json, false);
}

export function EntPhysicaltherapyrecordEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPhysicaltherapyrecordEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'personnel': !exists(json, 'Personnel') ? undefined : EntPersonnelFromJSON(json['Personnel']),
        'physicaltherapyroom': !exists(json, 'Physicaltherapyroom') ? undefined : EntPhysicaltherapyroomFromJSON(json['Physicaltherapyroom']),
        'status': !exists(json, 'Status') ? undefined : EntStatusFromJSON(json['Status']),
    };
}

export function EntPhysicaltherapyrecordEdgesToJSON(value?: EntPhysicaltherapyrecordEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient': EntPatientToJSON(value.patient),
        'personnel': EntPersonnelToJSON(value.personnel),
        'physicaltherapyroom': EntPhysicaltherapyroomToJSON(value.physicaltherapyroom),
        'status': EntStatusToJSON(value.status),
    };
}


