/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAntenatalinformation,
    EntAntenatalinformationFromJSON,
    EntAntenatalinformationFromJSONTyped,
    EntAntenatalinformationToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPregnancystatusEdges
 */
export interface EntPregnancystatusEdges {
    /**
     * 
     * @type {EntAntenatalinformation}
     * @memberof EntPregnancystatusEdges
     */
    antenatalinformation?: EntAntenatalinformation;
}

export function EntPregnancystatusEdgesFromJSON(json: any): EntPregnancystatusEdges {
    return EntPregnancystatusEdgesFromJSONTyped(json, false);
}

export function EntPregnancystatusEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPregnancystatusEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'antenatalinformation': !exists(json, 'antenatalinformation') ? undefined : EntAntenatalinformationFromJSON(json['antenatalinformation']),
    };
}

export function EntPregnancystatusEdgesToJSON(value?: EntPregnancystatusEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'antenatalinformation': EntAntenatalinformationToJSON(value.antenatalinformation),
    };
}


