/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPhysicaltherapyrecordEdges,
    EntPhysicaltherapyrecordEdgesFromJSON,
    EntPhysicaltherapyrecordEdgesFromJSONTyped,
    EntPhysicaltherapyrecordEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPhysicaltherapyrecord
 */
export interface EntPhysicaltherapyrecord {
    /**
     * AddedTime holds the value of the "added_time" field.
     * @type {string}
     * @memberof EntPhysicaltherapyrecord
     */
    addedTime?: string;
    /**
     * 
     * @type {EntPhysicaltherapyrecordEdges}
     * @memberof EntPhysicaltherapyrecord
     */
    edges?: EntPhysicaltherapyrecordEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPhysicaltherapyrecord
     */
    id?: number;
}

export function EntPhysicaltherapyrecordFromJSON(json: any): EntPhysicaltherapyrecord {
    return EntPhysicaltherapyrecordFromJSONTyped(json, false);
}

export function EntPhysicaltherapyrecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPhysicaltherapyrecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'added_time') ? undefined : json['added_time'],
        'edges': !exists(json, 'edges') ? undefined : EntPhysicaltherapyrecordEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPhysicaltherapyrecordToJSON(value?: EntPhysicaltherapyrecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added_time': value.addedTime,
        'edges': EntPhysicaltherapyrecordEdgesToJSON(value.edges),
        'id': value.id,
    };
}


