// Code generated by entc, DO NOT EDIT.

package risks

const (
	// Label holds the string label denoting the risks type in the database.
	Label = "risks"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRisks holds the string denoting the risks field in the database.
	FieldRisks = "risks"

	// EdgeAntenatalinformation holds the string denoting the antenatalinformation edge name in mutations.
	EdgeAntenatalinformation = "Antenatalinformation"

	// Table holds the table name of the risks in the database.
	Table = "risks"
	// AntenatalinformationTable is the table the holds the Antenatalinformation relation/edge.
	AntenatalinformationTable = "antenatalinformations"
	// AntenatalinformationInverseTable is the table name for the Antenatalinformation entity.
	// It exists in this package in order to avoid circular dependency with the "antenatalinformation" package.
	AntenatalinformationInverseTable = "antenatalinformations"
	// AntenatalinformationColumn is the table column denoting the Antenatalinformation relation/edge.
	AntenatalinformationColumn = "risks_antenatalinformation"
)

// Columns holds all SQL columns for risks fields.
var Columns = []string{
	FieldID,
	FieldRisks,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RisksValidator is a validator for the "Risks" field. It is called by the builders before save.
	RisksValidator func(string) error
)
